// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace master_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127085632_AddBlockFKs")]
    partial class AddBlockFKs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("master_backend.Models.ModelImplementations.BlockModels.Block", b =>
                {
                    b.Property<long>("blockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("blockId"));

                    b.Property<string>("blockDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("blockHTML")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("blockTitle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("blockId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.BlockModels.BlockContextWeight", b =>
                {
                    b.Property<long>("blockContextWeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("blockContextWeightId"));

                    b.Property<long>("baseBlockId")
                        .HasColumnType("bigint");

                    b.Property<long>("connectedBlockId")
                        .HasColumnType("bigint");

                    b.Property<int>("timesConnected")
                        .HasColumnType("integer");

                    b.HasKey("blockContextWeightId");

                    b.HasIndex("baseBlockId");

                    b.HasIndex("connectedBlockId");

                    b.ToTable("BlockContextWeights");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.BlockModels.BlockKeyword", b =>
                {
                    b.Property<long>("blockKeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("blockKeywordId"));

                    b.Property<string>("keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("blockKeywordId");

                    b.ToTable("BlockKeywords");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.BlockModels.BlockKeywordLink", b =>
                {
                    b.Property<long>("blockKeywordLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("blockKeywordLinkId"));

                    b.Property<long>("blockId")
                        .HasColumnType("bigint");

                    b.Property<long>("blockKeywordId")
                        .HasColumnType("bigint");

                    b.HasKey("blockKeywordLinkId");

                    b.HasIndex("blockId");

                    b.HasIndex("blockKeywordId");

                    b.ToTable("BlockKeywordLinks");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.FuzzyModels.CompanyWeight", b =>
                {
                    b.Property<long>("companyWeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("companyWeightId"));

                    b.Property<NpgsqlTsVector>("companyWeights")
                        .IsRequired()
                        .HasColumnType("tsvector");

                    b.HasKey("companyWeightId");

                    b.ToTable("CompanyWeights");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.FuzzyModels.FuzzyBlock", b =>
                {
                    b.Property<long>("fuzzyBlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("fuzzyBlockId"));

                    b.Property<long>("blockId")
                        .HasColumnType("bigint");

                    b.Property<NpgsqlTsVector>("businessAllignments")
                        .IsRequired()
                        .HasColumnType("tsvector");

                    b.Property<NpgsqlTsVector>("departmentAllignments")
                        .IsRequired()
                        .HasColumnType("tsvector");

                    b.HasKey("fuzzyBlockId");

                    b.HasIndex("blockId");

                    b.ToTable("FuzzyBlocks");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.FuzzyModels.UserWeight", b =>
                {
                    b.Property<long>("userWeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("userWeightId"));

                    b.Property<NpgsqlTsVector>("userWeights")
                        .IsRequired()
                        .HasColumnType("tsvector");

                    b.HasKey("userWeightId");

                    b.ToTable("UserWeights");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.GeneralModels.BusinessCategory", b =>
                {
                    b.Property<long>("BusinessCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BusinessCategoryID"));

                    b.Property<string>("BusinessCategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BusinessCategoryID");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.GeneralModels.Company", b =>
                {
                    b.Property<long>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.GeneralModels.DepartmentCategory", b =>
                {
                    b.Property<long>("DepartmentCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DepartmentCategoryID"));

                    b.Property<string>("DepartmentCategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("DepartmentCategoryID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.GeneralModels.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<long>("BusinessCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DepartmentCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("BusinessCategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentCategoryId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.BlockProbabilityHistory", b =>
                {
                    b.Property<long>("blockProbabilityHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("blockProbabilityHistoryId"));

                    b.Property<long>("blockId")
                        .HasColumnType("bigint");

                    b.Property<long>("businessCategoryProbabilityId")
                        .HasColumnType("bigint");

                    b.Property<long>("companyProbabilityId")
                        .HasColumnType("bigint");

                    b.Property<long>("departmentCategoryProbabilityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("lastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("probability")
                        .HasColumnType("real");

                    b.Property<long>("userProbabilityId")
                        .HasColumnType("bigint");

                    b.HasKey("blockProbabilityHistoryId");

                    b.HasIndex("blockId");

                    b.HasIndex("businessCategoryProbabilityId");

                    b.HasIndex("companyProbabilityId");

                    b.HasIndex("departmentCategoryProbabilityId");

                    b.HasIndex("userProbabilityId");

                    b.ToTable("BlockProbabilityHistories");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.BusinessCategoryAction", b =>
                {
                    b.Property<long>("businessCategoryActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("businessCategoryActionId"));

                    b.Property<long>("businessCategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("totalActions")
                        .HasColumnType("integer");

                    b.HasKey("businessCategoryActionId");

                    b.HasIndex("businessCategoryId");

                    b.ToTable("BusinessCategoryActions");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.BusinessCategoryProbability", b =>
                {
                    b.Property<long>("businessCategoryProbabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("businessCategoryProbabilityId"));

                    b.Property<long>("blockId")
                        .HasColumnType("bigint");

                    b.Property<long>("businessCategoryActionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("lastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("timesUsed")
                        .HasColumnType("integer");

                    b.HasKey("businessCategoryProbabilityId");

                    b.HasIndex("blockId");

                    b.HasIndex("businessCategoryActionId");

                    b.ToTable("BusinessCategoryProbabilities");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.CompanyAction", b =>
                {
                    b.Property<long>("companyActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("companyActionId"));

                    b.Property<long>("companyId")
                        .HasColumnType("bigint");

                    b.Property<int>("totalActions")
                        .HasColumnType("integer");

                    b.HasKey("companyActionId");

                    b.HasIndex("companyId");

                    b.ToTable("CompanyActions");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.CompanyProbability", b =>
                {
                    b.Property<long>("companyProbabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("companyProbabilityId"));

                    b.Property<long>("blockId")
                        .HasColumnType("bigint");

                    b.Property<long>("companyActionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("lastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("timesUsed")
                        .HasColumnType("integer");

                    b.HasKey("companyProbabilityId");

                    b.HasIndex("blockId");

                    b.HasIndex("companyActionId");

                    b.ToTable("CompanyProbabilities");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.DepartmentCategoryAction", b =>
                {
                    b.Property<long>("departmentCategoryActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("departmentCategoryActionId"));

                    b.Property<long>("departmentCategoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("totalActions")
                        .HasColumnType("integer");

                    b.HasKey("departmentCategoryActionId");

                    b.HasIndex("departmentCategoryId");

                    b.ToTable("DepartmentCategoryActions");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.DepartmentCategoryProbability", b =>
                {
                    b.Property<long>("departmentCategoryProbabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("departmentCategoryProbabilityId"));

                    b.Property<long>("blockId")
                        .HasColumnType("bigint");

                    b.Property<long>("departmentCategoryActionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("lastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("timesUsed")
                        .HasColumnType("integer");

                    b.HasKey("departmentCategoryProbabilityId");

                    b.HasIndex("blockId");

                    b.HasIndex("departmentCategoryActionId");

                    b.ToTable("DepartmentCategoryProbabilities");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.UserAction", b =>
                {
                    b.Property<long>("userActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("userActionId"));

                    b.Property<int>("totalActions")
                        .HasColumnType("integer");

                    b.Property<long>("userId")
                        .HasColumnType("bigint");

                    b.HasKey("userActionId");

                    b.HasIndex("userId");

                    b.ToTable("UserActions");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.UserProbability", b =>
                {
                    b.Property<long>("userProbabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("userProbabilityId"));

                    b.Property<long>("blockId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("lastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("timesUsed")
                        .HasColumnType("integer");

                    b.Property<long>("userActionId")
                        .HasColumnType("bigint");

                    b.HasKey("userProbabilityId");

                    b.HasIndex("blockId");

                    b.HasIndex("userActionId");

                    b.ToTable("UserProbabilities");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.BlockModels.BlockContextWeight", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "baseBlock")
                        .WithMany()
                        .HasForeignKey("baseBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "connectedBlock")
                        .WithMany()
                        .HasForeignKey("connectedBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("baseBlock");

                    b.Navigation("connectedBlock");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.BlockModels.BlockKeywordLink", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "block")
                        .WithMany()
                        .HasForeignKey("blockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.BlockKeyword", "BlockKeyword")
                        .WithMany()
                        .HasForeignKey("blockKeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockKeyword");

                    b.Navigation("block");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.FuzzyModels.FuzzyBlock", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "block")
                        .WithMany()
                        .HasForeignKey("blockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("block");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.GeneralModels.User", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.GeneralModels.BusinessCategory", "BusinessCategory")
                        .WithMany()
                        .HasForeignKey("BusinessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.GeneralModels.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.GeneralModels.DepartmentCategory", "DepartmentCategory")
                        .WithMany()
                        .HasForeignKey("DepartmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessCategory");

                    b.Navigation("Company");

                    b.Navigation("DepartmentCategory");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.BlockProbabilityHistory", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "block")
                        .WithMany()
                        .HasForeignKey("blockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.ProbabilityModels.BusinessCategoryProbability", "businessCategoryProbability")
                        .WithMany()
                        .HasForeignKey("businessCategoryProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.ProbabilityModels.CompanyProbability", "companyProbability")
                        .WithMany()
                        .HasForeignKey("companyProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.ProbabilityModels.DepartmentCategoryProbability", "departmentCategoryProbability")
                        .WithMany()
                        .HasForeignKey("departmentCategoryProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.ProbabilityModels.UserProbability", "userProbability")
                        .WithMany()
                        .HasForeignKey("userProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("block");

                    b.Navigation("businessCategoryProbability");

                    b.Navigation("companyProbability");

                    b.Navigation("departmentCategoryProbability");

                    b.Navigation("userProbability");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.BusinessCategoryAction", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.GeneralModels.BusinessCategory", "businessCategory")
                        .WithMany()
                        .HasForeignKey("businessCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("businessCategory");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.BusinessCategoryProbability", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "block")
                        .WithMany()
                        .HasForeignKey("blockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.ProbabilityModels.BusinessCategoryAction", "businessCategoryAction")
                        .WithMany()
                        .HasForeignKey("businessCategoryActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("block");

                    b.Navigation("businessCategoryAction");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.CompanyAction", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.GeneralModels.Company", "company")
                        .WithMany()
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.CompanyProbability", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "block")
                        .WithMany()
                        .HasForeignKey("blockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.ProbabilityModels.CompanyAction", "companyAction")
                        .WithMany()
                        .HasForeignKey("companyActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("block");

                    b.Navigation("companyAction");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.DepartmentCategoryAction", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.GeneralModels.DepartmentCategory", "departmentCategory")
                        .WithMany()
                        .HasForeignKey("departmentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("departmentCategory");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.DepartmentCategoryProbability", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "block")
                        .WithMany()
                        .HasForeignKey("blockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.ProbabilityModels.DepartmentCategoryAction", "departmentCategoryAction")
                        .WithMany()
                        .HasForeignKey("departmentCategoryActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("block");

                    b.Navigation("departmentCategoryAction");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.UserAction", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.GeneralModels.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("master_backend.Models.ModelImplementations.ProbabilityModels.UserProbability", b =>
                {
                    b.HasOne("master_backend.Models.ModelImplementations.BlockModels.Block", "block")
                        .WithMany()
                        .HasForeignKey("blockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("master_backend.Models.ModelImplementations.ProbabilityModels.UserAction", "userAction")
                        .WithMany()
                        .HasForeignKey("userActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("block");

                    b.Navigation("userAction");
                });
#pragma warning restore 612, 618
        }
    }
}
